//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class project1Entities : DbContext
    {
        public project1Entities()
            : base("name=project1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_signup> admin_signup { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<department1> department1 { get; set; }
        public virtual DbSet<user_register> user_register { get; set; }
    }
}
